name: MultiPlugin
main: com.jnngl.plugins.tools.Plugin
version: 2.0.026
author: JNNGL
commands:
   JNNJHL:
      description: One more compiler.
      usage: /JNNJHL <filename>
   JNNJHLmsg:
      description: JNNJHL compiler in minecraft.
      usage: /JNNJHLmsg <code>
   encode:
      description: QmFzZTY0IEVuY29kZXIg
      usage: /encode <text>
   decode:
      description: Base64 Decoder
      usage: /decode <text>
   UUID:
      description: Player's UUID
      usage: /UUID <player>
   ANSII:
      description: 065 078 083 073 073 032 069 110 099 111 100 101 114
      usage: /ANSII <text>
   fly:
      description: Fly?
      usage: /fly OR /fly <player>
   gmc:
      description: Creative
      usage: /gmc OR /gmc <player>
   gms:
      description: Survival
      usage: /gms OR /gms <player>
   gma:
      description: Adventure
      usage: /gma OR /gma <player>
   gmsp:
      description: Spectator
      usage: /gmsp OR /gmsp <player>
   gm:
      description: Gamemode
      usage: /gm <gamemode> OR /gm <gamemode> <player>
   feed:
      description: Full food level.
      usage: /feed OR /feed <player>
   heal:
      description: Full health level.
      usage: /heal OR /heal <player>
   afk:
      description: Away From Keyboard.
      usage: /afk
   script:
      description: What? Code compiler in a plugin!? Need's external library.
      usage: /script <filename>
   customtext:
      description: Floating text. Before this command, use textconfig command.
      usage: /customtext set <textname> OR /customtext remove <textname>
   textconfig:
      description: Setup for customtext command.
      usage: /textconfig add <textname> <text> OR /textconfig remove <textname>
   setwarp:
      description: Command to setup warp.
      usage: /setwarp <name>
   delwarp:
      description: Command to delete warp.
      usage: /delwarp <name>
   warps:
      description: Command to view warp list.
      usage: /warps
   warp:
      description: Command to teleport to warp.
      usage: /warp <name>
   sethome:
      description: Command to setup home.
      usage: /sethome <name>
   delhome:
      description: Command to delete home.
      usage: /delhome <name>
   home:
      description: Command to teleport to home.
      usage: /home <name>
   world:
      description: create world or teleport to other world.
      usage: /world create <FLAT:AMPLIFIED:LARGE_BIOMES:NORMAL> <World name> <generate structures (true:false)> OR /world tp <World name> OR /world tp <World name> <player>
   usual:
      description: OP or Member?
      usage: /usual <message>
   plus:
      description: plus!
      usage: /plus <num> <num>
   status:
      description: status....
      usage: /status set <status> or /status get <player>
   prefix:
      description: (YOUR PREFIX) (RANK) NAME (MESSAGE)
      usage: /prefix <prefix> or /prefix <prefix> <player>
   reset:
      description: Reset player prefix, suffix, chat allow/deny and advanced text allow/deny
      usage: /reset <player>
   rtp:
      description: Random Teleportation.
      usage: /rtp
   bcc:
      description: Advanced broadcast.
      usage: /bcc <message>
   suffix:
      description: (RANK) NAME (YOUR SUFFIX) (MESSAGE)
      usage: /suffix <suffix> or /suffix <suffix> <player>
   minus:
      description: minus!
      usage: /minus <num> <num>
   division:
      description: division!
      usage: /division <num> <num>
   multiply:
      description: multiply!
      usage: /multiply <num> <num>
   cos:
      description: COS!
      usage: /cos <number>
   sin:
      description: SIN!
      usage: /sin <number>
   java:
      description: ...
      usage: /java
   windows:
      description: ...
      usage: /windows
   NTFS:
      description: ...
      usage: /NTFS
   vsh:
      description: Vanish you.
      usage: /vsh
   bansh:
      description: Ban player.
      usage: /bansh <player> <reason>
   fakedeop:
      description: Tells "[Server ... De-pped]" to selected player
      usage: /fakedeop <player>
   broadcast:
      description: broadcast message. (Bukkit.broadcast(...);)
      usage: /broadcast <message>
   bc:
      description: broadcast message. (Bukkit.broadcast(...);)
      usage: /broadcast <message>
   warning:
      description: WARNING!
      usage: /warning <MESSAGE!>
   exec:
      description: arguments....
      usage: /exec <msg> <player> <message>
   firework:
      description: FireWorks!
      usage: /firework
   msg_console:
      description: Write in console "... wants to say something." or your message.
      usage: /msg_console
   tps:
      description: Teleport player to spawn.
      usage: /tps
   kit:
      description: Give selected kit to player.
      usage: /kit <type>
   chat:
      description: Allow/deny chat/advancedText to player
      usage: /chat <allow:deny> <chat:advanced> <player>
   mpt_effect:
      description: Display selected effect.
      usage: /effect <type> <times>
   info:
      description: Show to you, your statistics.
      usage: /info
   menu:
      description: Shows server menu
      usage: /menu
   trade:
      description: Main command for trading.
      usage: /trade <request:accept:deny> <playername>
   fakejoin:
      description: Tells "... joined!" to selected player
      usage: /fakejoin <PlayerToTell> <whoJoin>
   fakeleft:
      description: Tells "... has left!" to selected player
      usage: /fakeleft <PlayerToTell> <whoLeftn>
   fakeop:
      description: Tells "[Server ... Opped]" to selected player
      usage: /fakeop <player>
   getInv:
      description: ONLY FOR OPS! Opens selected player inventory.
      usage: /getInv <Player>